---
kind: pipeline
name: build

steps:
- name: build
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
    - go get -u github.com/pkg/errors
    - go get github.com/urfave/cli
    - go build -o drone-teams

- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_hub_user
    password: 
      from_secret: docker_hub_password
    repo: digitalwerber/drone-teams
    tags: latest


---
kind: signature
hmac: c8e124aa1a3c77b0ca02ee3f885a5813fcc8dff56bd9ed16bcf67213742490ca

...
