FROM microsoft/nanoserver:1803
USER ContainerAdministrator
ADD release/windows/amd64/drone-teams.exe /drone-teams.exe
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
ENTRYPOINT [ "\\drone-teams.exe" ]
