# escape=`
FROM plugins/base:windows-amd64

LABEL maintainer="Michael Müller <io@digitalwerber.de>" \
  org.label-schema.name="Drone Teams" \
  org.label-schema.vendor="Michael Müller" \
  org.label-schema.schema-version="1.0"

ADD release\drone-teams.exe c:\drone-teams.exe
ENTRYPOINT [ "c:\\drone-teams.exe" ]
